<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="customerManage.aspx.cs" Inherits="ERationCard.customerManage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridViewCust" runat="server" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
                    <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                    <asp:BoundField DataField="contactNo" HeaderText="contactNo" SortExpression="contactNo" />
                    <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Customer] WHERE [Id] = @original_Id AND [Name] = @original_Name AND [Gender] = @original_Gender AND [DOB] = @original_DOB AND [Address] = @original_Address AND [contactNo] = @original_contactNo AND [city] = @original_city" InsertCommand="INSERT INTO [Customer] ([Name], [Gender], [DOB], [Address], [contactNo], [city]) VALUES (@Name, @Gender, @DOB, @Address, @contactNo, @city)" SelectCommand="SELECT * FROM [Customer]" UpdateCommand="UPDATE [Customer] SET [Name] = @Name, [Gender] = @Gender, [DOB] = @DOB, [Address] = @Address, [contactNo] = @contactNo, [city] = @city WHERE [Id] = @original_Id AND [Name] = @original_Name AND [Gender] = @original_Gender AND [DOB] = @original_DOB AND [Address] = @original_Address AND [contactNo] = @original_contactNo AND [city] = @original_city" ConflictDetection="CompareAllValues" OldValuesParameterFormatString="original_{0}">
                <DeleteParameters>
                    <asp:Parameter Name="original_Id" Type="Int32" />
                    <asp:Parameter Name="original_Name" Type="String" />
                    <asp:Parameter Name="original_Gender" Type="String" />
                    <asp:Parameter DbType="Date" Name="original_DOB" />
                    <asp:Parameter Name="original_Address" Type="String" />
                    <asp:Parameter Name="original_contactNo" Type="Decimal" />
                    <asp:Parameter Name="original_city" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="DOB" DbType="Date" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="contactNo" Type="Decimal" />
                    <asp:Parameter Name="city" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Gender" Type="String" />
                    <asp:Parameter Name="DOB" DbType="Date" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="contactNo" Type="Decimal" />
                    <asp:Parameter Name="city" Type="String" />
                    <asp:Parameter Name="original_Id" Type="Int32" />
                    <asp:Parameter Name="original_Name" Type="String" />
                    <asp:Parameter Name="original_Gender" Type="String" />
                    <asp:Parameter DbType="Date" Name="original_DOB" />
                    <asp:Parameter Name="original_Address" Type="String" />
                    <asp:Parameter Name="original_contactNo" Type="Decimal" />
                    <asp:Parameter Name="original_city" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
            <asp:Label ID="lblCustomerName" runat="server" AssociatedControlID="tbCustomerName" Text="Name: "></asp:Label>
            <asp:TextBox ID="tbCustomerName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblCustomerGender" runat="server" AssociatedControlID="tbCustomerGender" Text="Gender: "></asp:Label>
&nbsp;
            <asp:TextBox ID="tbCustomerGender" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblCustomerDOB" runat="server" AssociatedControlID="tbCustomerDOB" Text="Date of birth: "></asp:Label>
&nbsp;
            <asp:TextBox ID="tbCustomerDOB" runat="server" TextMode="Date"></asp:TextBox>
            <br />
            <asp:Label ID="lblCustomerAddress" runat="server" AssociatedControlID="tbCustomerAddress" Text="Address: "></asp:Label>
            <asp:TextBox ID="tbCustomerAddress" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblCustomerNumber" runat="server" AssociatedControlID="tbCustomerNumber" Text="Mobile Number: "></asp:Label>
            <asp:TextBox ID="tbCustomerNumber" runat="server" TextMode="Number"></asp:TextBox>
            <br />
            <asp:Label ID="lblCustomerCity" runat="server" AssociatedControlID="tbCustomerCity" Text="City: "></asp:Label>
            <asp:TextBox ID="tbCustomerCity" runat="server"></asp:TextBox>
            <br />
            
            <asp:Button ID="btnAddCustomer" runat="server" Text="Add Customer" OnClick="btnAddShopkeeper_Click"/>
            <br />
            <br />
            <asp:Button ID="btnAdminLogOut" runat="server" OnClick="btnAdminLogOut_Click" Text="Logout" />
            <br />
        </div>
    </form>
</body>
</html>
