<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="shopkeeperManagement.aspx.cs" Inherits="ERationCard.shopkeeperManagement" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            margin-left: 40px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="auto-style1">
            <asp:GridView ID="GridViewShopkeeper" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="SqlDataSource1" >
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                    <asp:BoundField DataField="mobileNo" HeaderText="mobileNo" SortExpression="mobileNo" />
                    <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Shopkeeper] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Shopkeeper] ([Name], [Address], [mobileNo], [City]) VALUES (@Name, @Address, @mobileNo, @City)" SelectCommand="SELECT [Id], [Name], [Address], [mobileNo], [City] FROM [Shopkeeper]" UpdateCommand="UPDATE [Shopkeeper] SET [Name] = @Name, [Address] = @Address, [mobileNo] = @mobileNo, [City] = @City WHERE [Id] = @Id" >
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="mobileNo" Type="Decimal" />
                    <asp:Parameter Name="City" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="mobileNo" Type="Decimal" />
                    <asp:Parameter Name="City" Type="String" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:Label ID="lblShopkeeperName" runat="server" AssociatedControlID="tbShopkeeperName" Text="Name: "></asp:Label>
            <asp:TextBox ID="tbShopkeeperName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblShopkeeperAddress" runat="server" AssociatedControlID="tbShopkeeperAddress" Text="Address: "></asp:Label>
            <asp:TextBox ID="tbShopkeeperAddress" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblShopkeeperNumber" runat="server" AssociatedControlID="tbShopkeeperNumber" Text="Mobile Number: "></asp:Label>
            <asp:TextBox ID="tbShopkeeperNumber" runat="server" TextMode="Number"></asp:TextBox>
            <br />
            <asp:Label ID="lblShopkeeperCity" runat="server" AssociatedControlID="tbShopkeeperCity" Text="City: "></asp:Label>
            <asp:TextBox ID="tbShopkeeperCity" runat="server"></asp:TextBox>
            <br />
            
            <asp:Button ID="btnAddShopkeeper" runat="server" Text="Add Shopkeeper" OnClick="btnAddShopkeeper_Click"/>
            <br />
            <br />
            <asp:Button ID="btnAdminLogOut" runat="server" OnClick="btnAdminLogOut_Click" Text="Logout" />
        </div>
    </form>
</body>
</html>
