<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="shopkeeperHome.aspx.cs" Inherits="ERationCard.shopkeeperHome" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridViewProduct" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource1">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                </Columns>
            </asp:GridView>
            
            
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                SelectCommand="SELECT * FROM [Product]"
                UpdateCommand="UPDATE [Product] SET [Name] = @Name, [Price] = @Price WHERE [Id] = @Id"
                DeleteCommand="DELETE FROM [Product] WHERE [Id] = @Id"
                ></asp:SqlDataSource>
            
            
            <br />
            <asp:Label ID="lblProductName" runat="server" AssociatedControlID="tbProductName" Text="Name: "></asp:Label>
            <asp:TextBox ID="tbProductName" runat="server"></asp:TextBox>
            <br />
            <asp:Label ID="lblProductPrice" runat="server" AssociatedControlID="tbProductPrice" Text="Price: "></asp:Label>
            <asp:TextBox ID="tbProductPrice" runat="server" TextMode="Number"></asp:TextBox>
            <br />
            <asp:Button ID="btnAddProduct" runat="server" OnClick="btnAddProduct_Click" Text="Add Product"/>
            <br />
            <br />
            <asp:Button ID="btnSelectCust" runat="server" OnClick="btnSelectCust_Click" Text="Generate Bill" />
            <br />
                        <asp:Label ID="lblCustId" runat="server" Text="Customer ID: " Visible="False"></asp:Label>
                        <asp:DropDownList ID="ddlCustomer" runat="server" DataSourceID="SqlDataSource2" DataTextField="Id" DataValueField="Id" Visible="False">
                        </asp:DropDownList>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [Id] FROM [Customer]"></asp:SqlDataSource>
                    <br />
            <asp:Button ID="btnGenerateBill" runat="server" OnClick="btnGenerateBill_Click" Text="Continue" Visible="False" />
            <br />
            <br />
            <asp:Button ID="btnLogOut" runat="server" OnClick="btnLogOut_Click" Text="Log out" />
        </div>
    </form>
</body>
</html>
